### PR TITLE
TEPHRA-317 Add support for HBase 2.4

### PR DESCRIPTION
**Pull request by richardantal**

### CODE REVIEW

**Comment by stoty** [comment]
1. There seems to be a pom error that causes the test to fail.

2. Did you have to make changes in the code for 2.4 compared to 2.3 ? If not, then it'd be better to turn the 2.3 module into 2.3-base, and use that as a base for the actual 2.3 and 2.4 modules to avoid code duplication. (see the 2.0-base module for an example)

**Comment by richardantal** [comment]
> 1. There seems to be a pom error that causes the test to fail.
> 2. Did you have to make changes in the code for 2.4 compared to 2.3 ? If not, then it'd be better to turn the 2.3 module into 2.3-base, and use that as a base for the actual 2.3 and 2.4 modules to avoid code duplication. (see the 2.0-base module for an example)

1. Thanks, tephra-examples/tephra-examples-post-1.3/hbase-2.4/pom.xml was missing, locally it was fine but I forgot to add it to git.

2. I made 2 small code changes. One of them was in TransactionAwareHTable, there is a mutateRow function. It was void but now it returns Result type.
The second change is in the TransactionProcessorTest, the ChunkCreator function has an additional indexChunkSizePercent parameter.

**Comment by stoty** [comment]
Thanks.
Let's wait for the CI run.

**Review by stoty — APPROVED** [review]
+1 LGTM

**Pull request closed without merging**
